In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
f = open('/content/drive/MyDrive/datasets/employee.csv', 'w')
f.write('''Name,City,Age,Salary
Riya, Mumbai, 25, 50000
Arjun, Delhi, 32, 80000
Kabir, Mumbai, 45, 120000
Meera, Chennai, 28, 60000
Sam, Delhi, 38, 95000''')
f.close()

In [28]:
df = pd.read_csv('/content/drive/MyDrive/datasets/employee.csv')
df

    Name      City  Age  Salary
0   Riya    Mumbai   25   50000
1  Arjun     Delhi   32   80000
2  Kabir    Mumbai   45  120000
3  Meera   Chennai   28   60000
4    Sam     Delhi   38   95000

In [17]:
df.sort_values('Age')

    Name      City  Age  Salary
0   Riya    Mumbai   25   50000
3  Meera   Chennai   28   60000
1  Arjun     Delhi   32   80000
4    Sam     Delhi   38   95000
2  Kabir    Mumbai   45  120000

In [18]:
df.sort_values(["City", "Salary"])

    Name      City  Age  Salary
3  Meera   Chennai   28   60000
1  Arjun     Delhi   32   80000
4    Sam     Delhi   38   95000
0   Riya    Mumbai   25   50000
2  Kabir    Mumbai   45  120000

In [19]:
df.sort_values('Age', ascending = False)

    Name      City  Age  Salary
2  Kabir    Mumbai   45  120000
4    Sam     Delhi   38   95000
1  Arjun     Delhi   32   80000
3  Meera   Chennai   28   60000
0   Riya    Mumbai   25   50000

In [25]:
df.sort_values(["City", "Salary"], ascending=[True, False])

    Name      City  Age  Salary
3  Meera   Chennai   28   60000
4    Sam     Delhi   38   95000
1  Arjun     Delhi   32   80000
2  Kabir    Mumbai   45  120000
0   Riya    Mumbai   25   50000

In [26]:
df

    Name      City  Age  Salary
0   Riya    Mumbai   25   50000
1  Arjun     Delhi   32   80000
2  Kabir    Mumbai   45  120000
3  Meera   Chennai   28   60000
4    Sam     Delhi   38   95000

In [29]:
top3 = df.sort_values("Salary", ascending=False).head(3)
print(top3)

    Name     City  Age  Salary
2  Kabir   Mumbai   45  120000
4    Sam    Delhi   38   95000
1  Arjun    Delhi   32   80000

In [31]:
top3.loc[2]

Name        Kabir
City       Mumbai
Age            45
Salary     120000
Name: 2, dtype: object

In [22]:
# sorts the dataframe based on the index

df.sort_index()

    Name      City  Age  Salary
0   Riya    Mumbai   25   50000
1  Arjun     Delhi   32   80000
2  Kabir    Mumbai   45  120000
3  Meera   Chennai   28   60000
4    Sam     Delhi   38   95000

In [24]:
top3 = df.sort_values("Salary", ascending=False, ignore_index = True).head(3)
top3

    Name     City  Age  Salary
0  Kabir   Mumbai   45  120000
1    Sam    Delhi   38   95000
2  Arjun    Delhi   32   80000

In [53]:
f = open('/content/drive/MyDrive/datasets/employee.csv', 'w')
f.write('''Name,City,Category,Salary
Riya,Mumbai,IT,50000
Arjun,Delhi,HR,80000
Kabir,Mumbai,IT,120000
Meera,Chennai,HR,60000
Sam,Delhi,IT,95000
Neha,Mumbai,HR,70000''')
f.close()

In [54]:
df = pd.read_csv('/content/drive/MyDrive/datasets/employee.csv')
df

    Name     City Category  Salary
0   Riya   Mumbai       IT   50000
1  Arjun    Delhi       HR   80000
2  Kabir   Mumbai       IT  120000
3  Meera  Chennai       HR   60000
4    Sam    Delhi       IT   95000
5   Neha   Mumbai       HR   70000

In [56]:
# What's the total salary per city?
result = df.groupby("City")['Salary'].sum()
result

City
Chennai     60000
Delhi      175000
Mumbai     240000
Name: Salary, dtype: int64

In [57]:
# Avg sal, max, min, count

df.groupby("City")["Salary"].mean()

City
Chennai    60000.0
Delhi      87500.0
Mumbai     80000.0
Name: Salary, dtype: float64

In [58]:
df.groupby("City")["Salary"].max()

City
Chennai     60000
Delhi       95000
Mumbai     120000
Name: Salary, dtype: int64

In [59]:
df.groupby("City")["Salary"].min()

City
Chennai    60000
Delhi      80000
Mumbai     50000
Name: Salary, dtype: int64

In [60]:
df.groupby("City")["Salary"].count()

City
Chennai    1
Delhi      2
Mumbai     3
Name: Salary, dtype: int64

In [61]:
df.groupby("City").get_group('Mumbai')

    Name    City Category  Salary
0   Riya  Mumbai       IT   50000
2  Kabir  Mumbai       IT  120000
5   Neha  Mumbai       HR   70000

In [62]:
for ele in df.groupby("City"):
  print(ele)

('Chennai',     Name     City Category  Salary
3  Meera  Chennai       HR   60000)
('Delhi',     Name   City Category  Salary
1  Arjun  Delhi       HR   80000
4    Sam  Delhi       IT   95000)
('Mumbai',     Name    City Category  Salary
0   Riya  Mumbai       IT   50000
2  Kabir  Mumbai       IT  120000
5   Neha  Mumbai       HR   70000)

In [64]:
df

    Name     City Category  Salary
0   Riya   Mumbai       IT   50000
1  Arjun    Delhi       HR   80000
2  Kabir   Mumbai       IT  120000
3  Meera  Chennai       HR   60000
4    Sam    Delhi       IT   95000
5   Neha   Mumbai       HR   70000

In [63]:
result = df.groupby(["City", "Category"])["Salary"].sum()
print(result)

City     Category
Chennai  HR           60000
Delhi    HR           80000
         IT           95000
Mumbai   HR           70000
         IT          170000
Name: Salary, dtype: int64

In [67]:
result.loc['Mumbai']['HR']

np.int64(70000)

In [68]:
result = df.groupby("City")["Salary"].agg(["sum", "mean", "count", "max"])
print(result)

            sum     mean  count     max
City
Chennai   60000  60000.0      1   60000
Delhi    175000  87500.0      2   95000
Mumbai   240000  80000.0      3  120000

In [69]:
print(df["City"].value_counts())

City
Mumbai     3
Delhi      2
Chennai    1
Name: count, dtype: int64

In [ ]:
merge -> connecting the tables side by side
concatenating -> stacking the tables on top of each other

In [70]:
f = open('/content/drive/MyDrive/datasets/customers.csv', 'w')
f.write('''CustID,Name
101,Riya
102,Arjun
103,Kabir''')
f.close()

In [71]:
customers = pd.read_csv('/content/drive/MyDrive/datasets/customers.csv')
customers

   CustID   Name
0     101   Riya
1     102  Arjun
2     103  Kabir

In [77]:
f = open('/content/drive/MyDrive/datasets/orders.csv', 'w')
f.write('''CustID,Amount
101,500
103,1200
101,300
104,900''')
f.close()

In [78]:
orders = pd.read_csv('/content/drive/MyDrive/datasets/orders.csv')
orders

   CustID  Amount
0     101     500
1     103    1200
2     101     300
3     104     900

In [75]:
result = pd.merge(customers, orders, on="CustID")
print(result)

   CustID   Name  Amount
0     101   Riya     500
1     101   Riya     300
2     103  Kabir    1200

In [79]:
pd.merge(customers, orders, on="CustID", how="left")

   CustID   Name  Amount
0     101   Riya   500.0
1     101   Riya   300.0
2     102  Arjun     NaN
3     103  Kabir  1200.0

In [80]:
pd.merge(customers, orders, on="CustID", how="right")

   CustID   Name  Amount
0     101   Riya     500
1     103  Kabir    1200
2     101   Riya     300
3     104    NaN     900

In [81]:
pd.merge(customers, orders, on="CustID", how="inner")

   CustID   Name  Amount
0     101   Riya     500
1     101   Riya     300
2     103  Kabir    1200

In [82]:
pd.merge(customers, orders, on="CustID", how="outer")

   CustID   Name  Amount
0     101   Riya   500.0
1     101   Riya   300.0
2     102  Arjun     NaN
3     103  Kabir  1200.0
4     104    NaN   900.0

  - inner = only what's in both (the overlap).
  - left = everything on the left, plus matches.
  - right = everything on the right, plus matches.
  - outer = everything from both sides.

In [89]:
f = open('/content/drive/MyDrive/datasets/jan.csv', 'w')
f.write('''
Name,Sales
Riya,100
Arjun,200
''')
f.close()

In [90]:
f = open('/content/drive/MyDrive/datasets/feb.csv', 'w')
f.write('''
Name,Sales
Kabir,150
Meera,300
''')
f.close()

In [91]:
jan = pd.read_csv('/content/drive/MyDrive/datasets/jan.csv')
jan

    Name  Sales
0   Riya    100
1  Arjun    200

In [92]:
feb = pd.read_csv('/content/drive/MyDrive/datasets/feb.csv')
feb

    Name  Sales
0  Kabir    150
1  Meera    300

In [95]:
result = pd.concat([jan, feb])
print(result)

    Name  Sales
0   Riya    100
1  Arjun    200
0  Kabir    150
1  Meera    300

In [96]:
result.loc[1]

    Name  Sales
1  Arjun    200
1  Meera    300

# Datetime object

In [115]:
f = open('/content/drive/MyDrive/datasets/orders.csv', 'w')
f.write('''
OrderID,OrderDate,Amount
1,2024-01-15,500
2,2024-02-20,800
3,2024-02-28,300
4,2024-03-10,950
''')
f.close()

In [116]:
df = pd.read_csv('/content/drive/MyDrive/datasets/orders.csv', parse_dates=["OrderDate"])
df

   OrderID  OrderDate  Amount
0        1 2024-01-15     500
1        2 2024-02-20     800
2        3 2024-02-28     300
3        4 2024-03-10     950

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    4 non-null      int64
 1   OrderDate  4 non-null      datetime64[ns]
 2   Amount     4 non-null      int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 228.0 bytes

In [118]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])
print(df.dtypes)

OrderID               int64
OrderDate    datetime64[ns]
Amount                int64
dtype: object

In [119]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month
df["Day"] = df["OrderDate"].dt.day
df["DayName"] = df["OrderDate"].dt.day_name()
print(df)

   OrderID  OrderDate  Amount  Year  Month  Day    DayName
0        1 2024-01-15     500  2024      1   15     Monday
1        2 2024-02-20     800  2024      2   20    Tuesday
2        3 2024-02-28     300  2024      2   28  Wednesday
3        4 2024-03-10     950  2024      3   10     Sunday