In [478]:
import numpy as np
import pandas as pd

In [479]:
# from google.colab import drive

# drive.mount("/content/drive")

In [480]:
citi_bike_data = pd.read_csv('datasets/citibike_tripdata.csv')
citi_bike_data.head()

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber

In [481]:
# Access the trip data for all the rides where trip duration is more than 200 and usertype is subscriber
# and - &
# OR - |

new_citi_bike_data = citi_bike_data[(citi_bike_data['tripduration'] > 200) & (citi_bike_data['usertype'] == 'Subscriber')]
new_citi_bike_data

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [482]:
new_citi_bike_data[(new_citi_bike_data['start station name'] == 'Harborside') | (new_citi_bike_data['start station name'] == 'Newport PATH')]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
49,356,2018-05-01 06:40:07,2018-05-01 06:46:03,3639,Harborside,3202,Newport PATH,33618,Annual Membership,Subscriber
83,397,2018-05-01 07:10:27,2018-05-01 07:17:04,3639,Harborside,3205,JC Medical Center,26256,Annual Membership,Subscriber
187,232,2018-05-01 08:05:59,2018-05-01 08:09:52,3202,Newport PATH,3639,Harborside,33618,Annual Membership,Subscriber
192,281,2018-05-01 08:06:58,2018-05-01 08:11:40,3202,Newport PATH,3639,Harborside,33649,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32411,873,2018-05-30 13:29:58,2018-05-30 13:44:32,3639,Harborside,3220,5 Corners Library,29260,Annual Membership,Subscriber
32412,266,2018-05-30 13:30:11,2018-05-30 13:34:38,3639,Harborside,3202,Newport PATH,29461,$25 Off Annual Membership,Subscriber
32413,249,2018-05-30 13:35:14,2018-05-30 13:39:24,3639,Harborside,3184,Paulus Hook,29509,$25 Off Annual Membership,Subscriber
32415,279,2018-05-30 13:36:16,2018-05-30 13:40:55,3202,Newport PATH,3639,Harborside,29234,JCHA Annual Membership $5/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber

In [483]:
new_citi_bike_data[new_citi_bike_data['start station name'].isin(['Harborside', 'Newport PATH'])]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
49,356,2018-05-01 06:40:07,2018-05-01 06:46:03,3639,Harborside,3202,Newport PATH,33618,Annual Membership,Subscriber
83,397,2018-05-01 07:10:27,2018-05-01 07:17:04,3639,Harborside,3205,JC Medical Center,26256,Annual Membership,Subscriber
187,232,2018-05-01 08:05:59,2018-05-01 08:09:52,3202,Newport PATH,3639,Harborside,33618,Annual Membership,Subscriber
192,281,2018-05-01 08:06:58,2018-05-01 08:11:40,3202,Newport PATH,3639,Harborside,33649,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32411,873,2018-05-30 13:29:58,2018-05-30 13:44:32,3639,Harborside,3220,5 Corners Library,29260,Annual Membership,Subscriber
32412,266,2018-05-30 13:30:11,2018-05-30 13:34:38,3639,Harborside,3202,Newport PATH,29461,$25 Off Annual Membership,Subscriber
32413,249,2018-05-30 13:35:14,2018-05-30 13:39:24,3639,Harborside,3184,Paulus Hook,29509,$25 Off Annual Membership,Subscriber
32415,279,2018-05-30 13:36:16,2018-05-30 13:40:55,3202,Newport PATH,3639,Harborside,29234,JCHA Annual Membership $5/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber

In [484]:
citi_bike_data.loc[(citi_bike_data['tripduration'] > 200) & (citi_bike_data['usertype'] == 'Subscriber')].loc[::, ['start station name', 'end station name']]

          start station name end station name
0                 Harborside     Newport Pkwy
2            McGinley Square     Lincoln Park
4                Oakland Ave          Sip Ave
6      Baldwin at Montgomery    Grove St PATH
7                Oakland Ave        City Hall
...                      ...              ...
32423            Paulus Hook      Dixon Mills
32424           Newport PATH       Harborside
32425      5 Corners Library          Sip Ave
32426    Leonard Gordon Park   Van Vorst Park
32427      5 Corners Library      Oakland Ave

[24645 rows x 2 columns]

In [485]:
citi_bike_data.loc[(citi_bike_data['tripduration'] > 200) & (citi_bike_data['usertype'] == 'Subscriber'), ['start station name', 'end station name']]

          start station name end station name
0                 Harborside     Newport Pkwy
2            McGinley Square     Lincoln Park
4                Oakland Ave          Sip Ave
6      Baldwin at Montgomery    Grove St PATH
7                Oakland Ave        City Hall
...                      ...              ...
32423            Paulus Hook      Dixon Mills
32424           Newport PATH       Harborside
32425      5 Corners Library          Sip Ave
32426    Leonard Gordon Park   Van Vorst Park
32427      5 Corners Library      Oakland Ave

[24645 rows x 2 columns]

### Handling the Missing Value

In [486]:
weather_data = pd.read_csv('datasets/ny_weather.csv')
weather_data

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,NaN,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,NaN,8.0,NaN
7,1/10/2016,NaN,46.0,NaN,NaN,4.0,NaN,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,NaN,NaN
9,1/12/2016,35.0,NaN,53.0,29.85,10.0,6.0,NaN
10,1/13/2016,26.0,4.0,NaN,29.94,10.0,10.0,Rain
11,1/14/2016,NaN,12.0,47.0,NaN,NaN,NaN,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,NaN,Sunny

In [487]:
weather_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  14 non-null     str
 1   Temperature           11 non-null     float64
 2   DewPoint              11 non-null     float64
 3   Humidity              11 non-null     float64
 4   Sea Level PressureIn  11 non-null     float64
 5   VisibilityMiles       12 non-null     float64
 6   WindSpeedMPH          10 non-null     float64
 7   Event                 11 non-null     str
dtypes: float64(6), str(2)
memory usage: 1.0 KB

In [488]:
weather_data.isnull()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,True,True,False,False,False,False,False
3,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,True,False,False,False,False
6,False,False,False,False,False,True,False,True
7,False,True,False,True,True,False,True,False
8,False,False,False,False,False,False,True,True
9,False,False,True,False,False,False,False,True
10,False,False,False,True,False,False,False,False
11,False,True,False,False,True,True,True,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,False

In [489]:
weather_data.isnull().sum()

Date                    0
Temperature             3
DewPoint                3
Humidity                3
Sea Level PressureIn    3
VisibilityMiles         2
WindSpeedMPH            4
Event                   3
dtype: int64

In [490]:
weather_data.dropna()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow

In [491]:
weather_data.fillna(0)

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,0.0,0.0,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,0.0,35.0,0.00,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,0.0,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,0.0,8.0,0
7,1/10/2016,0.0,46.0,0.0,0.00,4.0,0.0,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,0.0,0
9,1/12/2016,35.0,0.0,53.0,29.85,10.0,6.0,0
10,1/13/2016,26.0,4.0,0.0,29.94,10.0,10.0,Rain
11,1/14/2016,0.0,12.0,47.0,0.00,0.0,0.0,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,0.0,Sunny

In [492]:
weather_data[['Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn', 'VisibilityMiles', 'WindSpeedMPH']] = weather_data[['Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn', 'VisibilityMiles', 'WindSpeedMPH']].fillna(0)

In [493]:
weather_data['Event'] = weather_data['Event'].fillna('No EVent')
weather_data

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,0.0,0.0,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,0.0,35.0,0.00,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,0.0,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,0.0,8.0,No EVent
7,1/10/2016,0.0,46.0,0.0,0.00,4.0,0.0,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,0.0,No EVent
9,1/12/2016,35.0,0.0,53.0,29.85,10.0,6.0,No EVent
10,1/13/2016,26.0,4.0,0.0,29.94,10.0,10.0,Rain
11,1/14/2016,0.0,12.0,47.0,0.00,0.0,0.0,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,0.0,Sunny

In [494]:
weather_data.fillna({'Temperature' : 0,
                         'DewPoint' : 0,
                         'Humidity' : 0,
             'Sea Level PressureIn' : 0,
                  'VisibilityMiles' : 0,
                     'WindSpeedMPH' : 0,
                            'Event' : "No Event"})

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,0.0,0.0,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,0.0,35.0,0.00,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,0.0,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,0.0,8.0,No EVent
7,1/10/2016,0.0,46.0,0.0,0.00,4.0,0.0,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,0.0,No EVent
9,1/12/2016,35.0,0.0,53.0,29.85,10.0,6.0,No EVent
10,1/13/2016,26.0,4.0,0.0,29.94,10.0,10.0,Rain
11,1/14/2016,0.0,12.0,47.0,0.00,0.0,0.0,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,0.0,Sunny

In [495]:
weather_data['Temperature'].interpolate()

0     38.0
1     36.0
2      0.0
3     33.0
4     39.0
5     39.0
6     44.0
7      0.0
8     33.0
9     35.0
10    26.0
11     0.0
12    36.0
13    25.0
Name: Temperature, dtype: float64

In [496]:
transaction_data = pd.read_csv('datasets/sample_data_customer_transaction_data.csv')

transaction_data

,transaction_id,transaction_date,transaction_time,transaction_amount,currency,payment_method,transaction_status,customer_id,customer_first_name,customer_last_name,...,product_subcategory,quantity,item_price,discount_applied_percent,store_id,shipping_address_city,shipping_address_state,shipping_address_country,device_used,ip_address
0,b08a9d98-986e-41ec-989e-4acc5f43accb,2024-10-06,19:42:37,$885.57,USD,Debit Card,Failed,a027c0bd-1edf-4a3f-b7ef-f5c58d20b8d3,Cody,Carson,...,Author,10.0,$125.88,29.65,STORE-015,Robertsmouth,HI,Canada,Desktop,13.236.93.137
1,96f2f3b9-a3a5-493d-a09d-dc8875c6d704,2021-05-17,03:37:08,$906.74,USD,Debit Card,Refunded,eaf947f0-a685-4afc-800b-f4e62524b6fc,Rebecca,Crawford,...,Check,3.0,$384.05,21.30,STORE-005,Erinfort,MO,USA,Desktop,206.121.97.119
2,92a55669-dfe0-4edd-9770-2680c4aac6f6,2025-06-06,17:58:09,"$1,669.43",USD,credit_card,Refunded,47f33a62-e619-4aaf-a5c5-d4533f25e574,Heather,Mccall,...,End,7.0,$258.33,7.68,STORE-019,Nguyenburgh,MO,USA,Tablet,209.5.67.244
3,7dc592f6-c821-4318-8607-bf776147a910,2024-11-13,05:45:45,"$3,199.98",USD,Bank Transfer,Completed,195f9373-4509-4938-9c0f-8c809b7694a8,Douglas,Walsh,...,Lead,7.0,$477.48,4.26,STORE-009,New Ronaldview,MN,U.S.A.,Tablet,130.83.249.234
4,ad969b12-6f09-4a10-a911-90bc9f6953ad,2023-06-29,04:04:51,"$2,757.83",USD,Debit Card,Pending,0ed676db-664d-4ef8-8ce1-dc788f0c2bb7,Lisa,Stephenson,...,Glass,10.0,$372.63,25.99,STORE-020,South Mandy,FM,CAN,Tablet,191.67.255.253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,f3207d67-c909-45a3-8ca5-8a22b52740e0,2024-03-23,05:21:58,$222.96,USD,Debit Card,Completed,4febfb33-60a4-4e53-b3a9-44318a604871,Sarah,Keith,...,Then,1.0,$279.29,20.17,STORE-013,Lake Rhondaside,NH,UK,Tablet,68.63.149.33
1026,c0f2b4e4-7dde-4f7e-9aed-a6bdb1905e84,2024-04-24,09:18:04,$179.13,USD,paypal,Completed,015fbd46-c368-4c33-98f6-a45b37b1f924,Mallory,Flores,...,Common,1.0,$251.66,28.82,STORE-017,New Johnberg,OR,CAN,Tablet,55.236.129.235
1027,ddff9288-6e3d-45c0-916e-b95556c1c17c,2023-05-21,23:04:34,$385.78,USD,CC,Pending,085f3175-bd80-4ad2-9139-28ed337eef69,Randy,Martinez,...,Easy,2.0,$265.65,27.39,STORE-012,Lake Jessica,AS,USA,Tablet,38.127.162.107
1028,8e62364b-8260-454f-9a27-dab217339185,2025-01-31,17:21:50,$72.11,USD,CC,Failed,47f33a62-e619-4aaf-a5c5-d4533f25e574,Sydney,Phillips,...,Account,4.0,$23.64,23.74,STORE-003,Taylorfort,NE,United States,Tablet,36.59.196.76
1029,c320bd9e-e48f-4c0c-b818-7bf8ceb0e331,2024-06-15,15:01:18,"$1,781.14",USD,PayPal,Refunded,325e352d-ea7d-4daa-b21f-c580f21e0c49,Laura,Nguyen,...,Summer,7.0,$348.99,27.09,STORE-002,Myersberg,AZ,United States,Desktop,15.174.206.71

In [497]:
transaction_data.duplicated().sum()

np.int64(30)

In [498]:
transaction_data.drop_duplicates()

,transaction_id,transaction_date,transaction_time,transaction_amount,currency,payment_method,transaction_status,customer_id,customer_first_name,customer_last_name,...,product_subcategory,quantity,item_price,discount_applied_percent,store_id,shipping_address_city,shipping_address_state,shipping_address_country,device_used,ip_address
0,b08a9d98-986e-41ec-989e-4acc5f43accb,2024-10-06,19:42:37,$885.57,USD,Debit Card,Failed,a027c0bd-1edf-4a3f-b7ef-f5c58d20b8d3,Cody,Carson,...,Author,10.0,$125.88,29.65,STORE-015,Robertsmouth,HI,Canada,Desktop,13.236.93.137
1,96f2f3b9-a3a5-493d-a09d-dc8875c6d704,2021-05-17,03:37:08,$906.74,USD,Debit Card,Refunded,eaf947f0-a685-4afc-800b-f4e62524b6fc,Rebecca,Crawford,...,Check,3.0,$384.05,21.30,STORE-005,Erinfort,MO,USA,Desktop,206.121.97.119
2,92a55669-dfe0-4edd-9770-2680c4aac6f6,2025-06-06,17:58:09,"$1,669.43",USD,credit_card,Refunded,47f33a62-e619-4aaf-a5c5-d4533f25e574,Heather,Mccall,...,End,7.0,$258.33,7.68,STORE-019,Nguyenburgh,MO,USA,Tablet,209.5.67.244
3,7dc592f6-c821-4318-8607-bf776147a910,2024-11-13,05:45:45,"$3,199.98",USD,Bank Transfer,Completed,195f9373-4509-4938-9c0f-8c809b7694a8,Douglas,Walsh,...,Lead,7.0,$477.48,4.26,STORE-009,New Ronaldview,MN,U.S.A.,Tablet,130.83.249.234
4,ad969b12-6f09-4a10-a911-90bc9f6953ad,2023-06-29,04:04:51,"$2,757.83",USD,Debit Card,Pending,0ed676db-664d-4ef8-8ce1-dc788f0c2bb7,Lisa,Stephenson,...,Glass,10.0,$372.63,25.99,STORE-020,South Mandy,FM,CAN,Tablet,191.67.255.253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,f3207d67-c909-45a3-8ca5-8a22b52740e0,2024-03-23,05:21:58,$222.96,USD,Debit Card,Completed,4febfb33-60a4-4e53-b3a9-44318a604871,Sarah,Keith,...,Then,1.0,$279.29,20.17,STORE-013,Lake Rhondaside,NH,UK,Tablet,68.63.149.33
1026,c0f2b4e4-7dde-4f7e-9aed-a6bdb1905e84,2024-04-24,09:18:04,$179.13,USD,paypal,Completed,015fbd46-c368-4c33-98f6-a45b37b1f924,Mallory,Flores,...,Common,1.0,$251.66,28.82,STORE-017,New Johnberg,OR,CAN,Tablet,55.236.129.235
1027,ddff9288-6e3d-45c0-916e-b95556c1c17c,2023-05-21,23:04:34,$385.78,USD,CC,Pending,085f3175-bd80-4ad2-9139-28ed337eef69,Randy,Martinez,...,Easy,2.0,$265.65,27.39,STORE-012,Lake Jessica,AS,USA,Tablet,38.127.162.107
1028,8e62364b-8260-454f-9a27-dab217339185,2025-01-31,17:21:50,$72.11,USD,CC,Failed,47f33a62-e619-4aaf-a5c5-d4533f25e574,Sydney,Phillips,...,Account,4.0,$23.64,23.74,STORE-003,Taylorfort,NE,United States,Tablet,36.59.196.76
1029,c320bd9e-e48f-4c0c-b818-7bf8ceb0e331,2024-06-15,15:01:18,"$1,781.14",USD,PayPal,Refunded,325e352d-ea7d-4daa-b21f-c580f21e0c49,Laura,Nguyen,...,Summer,7.0,$348.99,27.09,STORE-002,Myersberg,AZ,United States,Desktop,15.174.206.71

In [499]:
transaction_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   transaction_id            1030 non-null   str
 1   transaction_date          1030 non-null   str
 2   transaction_time          1030 non-null   str
 3   transaction_amount        1030 non-null   str
 4   currency                  1030 non-null   str
 5   payment_method            1030 non-null   str
 6   transaction_status        1030 non-null   str
 7   customer_id               1030 non-null   str
 8   customer_first_name       1030 non-null   str
 9   customer_last_name        1030 non-null   str
 10  customer_email            1030 non-null   str
 11  customer_phone            1030 non-null   str
 12  customer_dob              953 non-null    str
 13  customer_gender           958 non-null    str
 14  account_creation_date     1030 non-null   str
 15  last_login_date           957 non-null    str
 16  loyalty_program_member    1030 non-null   str
 17  product_id                1030 non-null   str
 18  product_name              1030 non-null   str
 19  product_category          1030 non-null   str
 20  product_subcategory       1030 non-null   str
 21  quantity                  1007 non-null   float64
 22  item_price                1030 non-null   str
 23  discount_applied_percent  1030 non-null   float64
 24  store_id                  1030 non-null   str
 25  shipping_address_city     1030 non-null   str
 26  shipping_address_state    964 non-null    str
 27  shipping_address_country  1030 non-null   str
 28  device_used               1030 non-null   str
 29  ip_address                1030 non-null   str
dtypes: float64(2), str(28)
memory usage: 241.5 KB

In [500]:
transaction_data['transaction_amount'] = transaction_data['transaction_amount'].replace({r'[$,]':''}, regex = True).astype(float)
transaction_data['transaction_amount']

0        885.57
1        906.74
2       1669.43
3       3199.98
4       2757.83
         ...
1025     222.96
1026     179.13
1027     385.78
1028      72.11
1029    1781.14
Name: transaction_amount, Length: 1030, dtype: float64

### Renaming the columns

In [501]:
weather_data = weather_data.rename(columns = {'Sea Level PressureIn':'SeaLevelPressureIn'})
weather_data

,Date,Temperature,DewPoint,Humidity,SeaLevelPressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,0.0,0.0,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,0.0,35.0,0.00,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,0.0,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,0.0,8.0,No EVent
7,1/10/2016,0.0,46.0,0.0,0.00,4.0,0.0,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,0.0,No EVent
9,1/12/2016,35.0,0.0,53.0,29.85,10.0,6.0,No EVent
10,1/13/2016,26.0,4.0,0.0,29.94,10.0,10.0,Rain
11,1/14/2016,0.0,12.0,47.0,0.00,0.0,0.0,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,0.0,Sunny

<!-- Steps
1=> Data Loading
2=> Data Understanding
3=> Data Cleaning
4=> Data Processing -->

In [502]:
# Steps
# 1 => Data Loading
# 2 => Data Understanding
# 3 => Data Cleaning
# 4 => Data Processing
# 5 => Data Analysis

### Changing or Adding the Data

In [503]:
df = pd.read_csv('datasets/test.csv')
df

       Name  Price  Quantity     Category
0       Pen     10       100   stationery
1    Laptop  50000         3  electronics
2  Notebook     40        50   stationery
3     Phone  20000         8  electronics

In [504]:
df["Total"] = df["Price"] * df["Quantity"]
print(df)

       Name  Price  Quantity     Category   Total
0       Pen     10       100   stationery    1000
1    Laptop  50000         3  electronics  150000
2  Notebook     40        50   stationery    2000
3     Phone  20000         8  electronics  160000

In [505]:
df["GST"] = df["Total"] * 0.18
df["Total_with_GST"] = df["Total"] + df["GST"]
print(df)

       Name  Price  Quantity     Category   Total      GST  Total_with_GST
0       Pen     10       100   stationery    1000    180.0          1180.0
1    Laptop  50000         3  electronics  150000  27000.0        177000.0
2  Notebook     40        50   stationery    2000    360.0          2360.0
3     Phone  20000         8  electronics  160000  28800.0        188800.0

In [506]:
def price_label (price):
    if price <100:
        return "Cheap"
    else: 
        return "Costly"

In [507]:
df ["PriceType"] = df["Price"].apply(price_label)
df

,Name,Price,Quantity,Category,Total,GST,Total_with_GST,PriceType
0,Pen,10,100,stationery,1000,180.0,1180.0,Cheap
1,Laptop,50000,3,electronics,150000,27000.0,177000.0,Costly
2,Notebook,40,50,stationery,2000,360.0,2360.0,Cheap
3,Phone,20000,8,electronics,160000,28800.0,188800.0,Costly

In [508]:
# df ["PriceType"] = df["Price"].apply(lambda price: 'Cheap' if price < 100 else 'Costly')

In [509]:
df["CategoryShort"] = df["Category"].map({
    "stationery": "STAT",
    "electronics": "ELEC"
})
df

,Name,Price,Quantity,Category,Total,GST,Total_with_GST,PriceType,CategoryShort
0,Pen,10,100,stationery,1000,180.0,1180.0,Cheap,STAT
1,Laptop,50000,3,electronics,150000,27000.0,177000.0,Costly,ELEC
2,Notebook,40,50,stationery,2000,360.0,2360.0,Cheap,STAT
3,Phone,20000,8,electronics,160000,28800.0,188800.0,Costly,ELEC

In [510]:
df["Category"] = df["Category"].replace("stationery", "office_supplies")

df

,Name,Price,Quantity,Category,Total,GST,Total_with_GST,PriceType,CategoryShort
0,Pen,10,100,office_supplies,1000,180.0,1180.0,Cheap,STAT
1,Laptop,50000,3,electronics,150000,27000.0,177000.0,Costly,ELEC
2,Notebook,40,50,office_supplies,2000,360.0,2360.0,Cheap,STAT
3,Phone,20000,8,electronics,160000,28800.0,188800.0,Costly,ELEC

In [511]:
df["NameUpper"] = df["Name"].str.upper()
df["NameLength"] = df["Name"].str.len()
df["HasO"] = df["Name"].str.contains("o")
print(df)

       Name  Price  Quantity         Category   Total      GST  \
0       Pen     10       100  office_supplies    1000    180.0
1    Laptop  50000         3      electronics  150000  27000.0
2  Notebook     40        50  office_supplies    2000    360.0
3     Phone  20000         8      electronics  160000  28800.0

   Total_with_GST PriceType CategoryShort NameUpper  NameLength   HasO
0          1180.0     Cheap          STAT       PEN           3  False
1        177000.0    Costly          ELEC    LAPTOP           6   True
2          2360.0     Cheap          STAT  NOTEBOOK           8   True
3        188800.0    Costly          ELEC     PHONE           5   True

### Dropping the Column

In [512]:
df = df.drop(columns=["CategoryShort", "HasO"])
df

,Name,Price,Quantity,Category,Total,GST,Total_with_GST,PriceType,NameUpper,NameLength
0,Pen,10,100,office_supplies,1000,180.0,1180.0,Cheap,PEN,3
1,Laptop,50000,3,electronics,150000,27000.0,177000.0,Costly,LAPTOP,6
2,Notebook,40,50,office_supplies,2000,360.0,2360.0,Cheap,NOTEBOOK,8
3,Phone,20000,8,electronics,160000,28800.0,188800.0,Costly,PHONE,5