In [2]:
import numpy as np
import pandas as pd

In [ ]:
Series - Data With one columns
DataFrame - Data with multiple columns

In [3]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [6]:
# How a dataframe looks like
crime_data = pd.read_csv('/content/drive/MyDrive/datasets/Crime in the United States.csv')
crime_data

,Year,Violent Crime Rate,Robbery Rate,Property Crime Rate,Burglary Rate,Larceny Theft Rate,Vehicle Theft Rate
0,2000,506.5,145.0,3618.3,728.8,2477.3,412.2
1,2001,504.5,148.5,3658.1,741.8,2485.7,430.5
2,2002,494.4,146.1,3630.6,747.0,2450.7,432.9
3,2003,475.8,142.5,3591.2,741.0,2416.5,433.7
4,2004,463.2,136.7,3514.1,730.3,2362.3,421.5
5,2005,469.0,140.8,3431.5,726.9,2287.8,416.8
6,2006,479.3,150.0,3346.6,733.1,2213.2,400.2
7,2007,471.8,148.3,3276.4,726.1,2185.4,364.9
8,2008,458.6,145.9,3214.6,733.0,2166.1,315.4
9,2009,431.9,133.1,3041.3,717.7,2064.5,259.2
10,2010,404.5,119.3,2945.9,701.0,2005.8,239.1
11,2011,387.1,113.9,2905.4,701.3,1974.1,230.0
12,2012,387.8,113.1,2868.0,672.2,1965.4,230.4
13,2013,367.9,109.1,2730.7,610.0,1899.4,221.3

In [9]:
crime_data['Violent Crime Rate']

0     506.5
1     504.5
2     494.4
3     475.8
4     463.2
5     469.0
6     479.3
7     471.8
8     458.6
9     431.9
10    404.5
11    387.1
12    387.8
13    367.9
Name: Violent Crime Rate, dtype: float64

In [7]:
river = ['Missouri', 'Mississippi', 'Yukon',
         'Tennessee', 'Brazos']

In [8]:
river_ser = pd.Series(river)
print(river_ser)

0       Missouri
1    Mississippi
2          Yukon
3      Tennessee
4         Brazos
dtype: object

In [11]:
(river_ser[0])

'Missouri'

In [13]:
river_ser[-1]

KeyError: -1

In [15]:
river_ser

0       Missouri
1    Mississippi
2          Yukon
3      Tennessee
4         Brazos
dtype: object

In [16]:
print(river_ser[1:3])

1    Mississippi
2          Yukon
dtype: object

In [17]:
ser_river = pd.Series(river, ['riv_'+str(i) for i in range(1, len(river)+1)])
ser_river

riv_1       Missouri
riv_2    Mississippi
riv_3          Yukon
riv_4      Tennessee
riv_5         Brazos
dtype: object

In [18]:
ser_river.rename('River_name')

riv_1       Missouri
riv_2    Mississippi
riv_3          Yukon
riv_4      Tennessee
riv_5         Brazos
Name: River_name, dtype: object

In [19]:
print(ser_river['riv_2'])

Mississippi

In [ ]:
# In the case of custom indexing, stop index is also included in slicing
# whereas in case of 0 based indexing stop index is not included in slicing

In [20]:
print(ser_river['riv_2':'riv_4'])

riv_2    Mississippi
riv_3          Yukon
riv_4      Tennessee
dtype: object

In [21]:
print(ser_river[1:4])

riv_2    Mississippi
riv_3          Yukon
riv_4      Tennessee
dtype: object

In [23]:
sales_data = {2000:'89 Cr', 2005:'159 Cr', 2010:'279 Cr', 2015:'300 Cr', 2020:'315 Cr'}
sales_data

{2000: '89 Cr', 2005: '159 Cr', 2010: '279 Cr', 2015: '300 Cr', 2020: '315 Cr'}

In [24]:
pd.Series(sales_data)

2000     89 Cr
2005    159 Cr
2010    279 Cr
2015    300 Cr
2020    315 Cr
dtype: object

In [26]:
data = {
    "Name": ["Riya", "Arjun", "Kabir"],
    "Maths": [85, 60, 95],
    "Science": [90, 75],
    "English": [70, 80, 92]
}
df = pd.DataFrame(data)
print(df)

ValueError: All arrays must be of the same length

In [27]:
crime_data

,Year,Violent Crime Rate,Robbery Rate,Property Crime Rate,Burglary Rate,Larceny Theft Rate,Vehicle Theft Rate
0,2000,506.5,145.0,3618.3,728.8,2477.3,412.2
1,2001,504.5,148.5,3658.1,741.8,2485.7,430.5
2,2002,494.4,146.1,3630.6,747.0,2450.7,432.9
3,2003,475.8,142.5,3591.2,741.0,2416.5,433.7
4,2004,463.2,136.7,3514.1,730.3,2362.3,421.5
5,2005,469.0,140.8,3431.5,726.9,2287.8,416.8
6,2006,479.3,150.0,3346.6,733.1,2213.2,400.2
7,2007,471.8,148.3,3276.4,726.1,2185.4,364.9
8,2008,458.6,145.9,3214.6,733.0,2166.1,315.4
9,2009,431.9,133.1,3041.3,717.7,2064.5,259.2
10,2010,404.5,119.3,2945.9,701.0,2005.8,239.1
11,2011,387.1,113.9,2905.4,701.3,1974.1,230.0
12,2012,387.8,113.1,2868.0,672.2,1965.4,230.4
13,2013,367.9,109.1,2730.7,610.0,1899.4,221.3

In [30]:
crime_data.head(10)

,Year,Violent Crime Rate,Robbery Rate,Property Crime Rate,Burglary Rate,Larceny Theft Rate,Vehicle Theft Rate
0,2000,506.5,145.0,3618.3,728.8,2477.3,412.2
1,2001,504.5,148.5,3658.1,741.8,2485.7,430.5
2,2002,494.4,146.1,3630.6,747.0,2450.7,432.9
3,2003,475.8,142.5,3591.2,741.0,2416.5,433.7
4,2004,463.2,136.7,3514.1,730.3,2362.3,421.5
5,2005,469.0,140.8,3431.5,726.9,2287.8,416.8
6,2006,479.3,150.0,3346.6,733.1,2213.2,400.2
7,2007,471.8,148.3,3276.4,726.1,2185.4,364.9
8,2008,458.6,145.9,3214.6,733.0,2166.1,315.4
9,2009,431.9,133.1,3041.3,717.7,2064.5,259.2

In [29]:
crime_data.tail()

,Year,Violent Crime Rate,Robbery Rate,Property Crime Rate,Burglary Rate,Larceny Theft Rate,Vehicle Theft Rate
9,2009,431.9,133.1,3041.3,717.7,2064.5,259.2
10,2010,404.5,119.3,2945.9,701.0,2005.8,239.1
11,2011,387.1,113.9,2905.4,701.3,1974.1,230.0
12,2012,387.8,113.1,2868.0,672.2,1965.4,230.4
13,2013,367.9,109.1,2730.7,610.0,1899.4,221.3

In [31]:
crime_data.shape

(14, 7)

In [32]:
crime_data.columns

Index(['Year', 'Violent Crime Rate', 'Robbery Rate', 'Property Crime Rate',
       'Burglary Rate', 'Larceny Theft Rate', 'Vehicle Theft Rate'],
      dtype='object')

In [33]:
crime_data.dtypes

Year                     int64
Violent Crime Rate     float64
Robbery Rate           float64
Property Crime Rate    float64
Burglary Rate          float64
Larceny Theft Rate     float64
Vehicle Theft Rate     float64
dtype: object

In [34]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 14 non-null     int64
 1   Violent Crime Rate   14 non-null     float64
 2   Robbery Rate         14 non-null     float64
 3   Property Crime Rate  14 non-null     float64
 4   Burglary Rate        14 non-null     float64
 5   Larceny Theft Rate   14 non-null     float64
 6   Vehicle Theft Rate   14 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 916.0 bytes

In [35]:
crime_data.describe()

,Year,Violent Crime Rate,Robbery Rate,Property Crime Rate,Burglary Rate,Larceny Theft Rate,Vehicle Theft Rate
count,14.0000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000
mean,2006.5000,450.164286,135.164286,3269.478571,715.014286,2211.014286,343.435714
std,4.1833,46.164899,14.843523,321.355708,36.169491,206.552857,88.989598
min,2000.0000,367.900000,109.100000,2730.700000,610.000000,1899.400000,221.300000
25%,2003.2500,411.350000,122.750000,2969.750000,705.400000,2020.475000,244.125000
50%,2006.5000,466.100000,141.650000,3311.500000,727.850000,2199.300000,382.550000
75%,2009.7500,478.425000,146.050000,3571.925000,733.075000,2402.950000,420.325000
max,2013.0000,506.500000,150.000000,3658.100000,747.000000,2485.700000,433.700000

In [36]:
# Selecting and Filtering the data

citi_bike_data = pd.read_csv('/content/drive/MyDrive/datasets/citibike_tripdata.csv')
citi_bike_data.shape

(32428, 10)

In [37]:
citi_bike_data.head()

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber

In [38]:
citi_bike_data['tripduration']

0         338
1        1482
2         232
3         190
4         303
         ...
32423     396
32424     313
32425     316
32426    1130
32427     369
Name: tripduration, Length: 32428, dtype: int64

In [39]:
citi_bike_data[['tripduration', 'starttime', 'stoptime']]

       tripduration            starttime             stoptime
0               338  2018-05-01 00:04:47  2018-05-01 00:10:25
1              1482  2018-05-01 01:31:10  2018-05-01 01:55:53
2               232  2018-05-01 01:31:29  2018-05-01 01:35:22
3               190  2018-05-01 02:03:29  2018-05-01 02:06:40
4               303  2018-05-01 04:27:12  2018-05-01 04:32:16
...             ...                  ...                  ...
32423           396  2018-05-30 13:49:18  2018-05-30 13:55:55
32424           313  2018-05-30 13:49:21  2018-05-30 13:54:35
32425           316  2018-05-30 13:49:51  2018-05-30 13:55:08
32426          1130  2018-05-30 13:50:52  2018-05-30 14:09:42
32427           369  2018-05-30 13:50:58  2018-05-30 13:57:08

[32428 rows x 3 columns]

In [ ]:
#df.loc[]
#df.iloc[]

In [41]:
# citi_bike_data[0]

In [42]:
citi_bike_data.loc[0]

tripduration                           338
starttime              2018-05-01 00:04:47
stoptime               2018-05-01 00:10:25
start station id                      3639
start station name              Harborside
end station id                        3199
end station name              Newport Pkwy
bikeid                               33558
name_localizedValue      Annual Membership
usertype                        Subscriber
Name: 0, dtype: object

In [43]:
# We use loc when we know name or label of row or column index

citi_bike_data.loc[1:10]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber
10,353,2018-05-01 05:18:36,2018-05-01 05:24:29,3225,Baldwin at Montgomery,3195,Sip Ave,33627,Annual Membership,Subscriber

In [44]:
# We use .loc when we use the built-in row or columns index
citi_bike_data.iloc[1:10]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [46]:
new_citi_bike_data= citi_bike_data.head(10)
new_citi_bike_data

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [47]:
new_citi_bike_data.index = ['ride_'+str(i) for i in range(1, 11)]
new_citi_bike_data

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
ride_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
ride_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
ride_10,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [48]:
citi_bike_data

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [51]:
new_citi_bike_data.loc['ride_1']

tripduration                           338
starttime              2018-05-01 00:04:47
stoptime               2018-05-01 00:10:25
start station id                      3639
start station name              Harborside
end station id                        3199
end station name              Newport Pkwy
bikeid                               33558
name_localizedValue      Annual Membership
usertype                        Subscriber
Name: ride_1, dtype: object

In [52]:
new_citi_bike_data.loc['ride_1':'ride_5']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
ride_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber

In [54]:
new_citi_bike_data.iloc[0]

tripduration                           338
starttime              2018-05-01 00:04:47
stoptime               2018-05-01 00:10:25
start station id                      3639
start station name              Harborside
end station id                        3199
end station name              Newport Pkwy
bikeid                               33558
name_localizedValue      Annual Membership
usertype                        Subscriber
Name: ride_1, dtype: object

In [55]:
new_citi_bike_data.iloc[0:5]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
ride_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber

In [57]:
new_citi_bike_data.loc[::, 'tripduration':'bikeid']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
ride_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
ride_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300
ride_10,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555

In [58]:
new_citi_bike_data.loc[::, ::]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
ride_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
ride_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
ride_10,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber

In [59]:
new_citi_bike_data.loc[::, ::2]

,tripduration,stoptime,start station name,end station name,name_localizedValue
ride_1,338,2018-05-01 00:10:25,Harborside,Newport Pkwy,Annual Membership
ride_2,1482,2018-05-01 01:55:53,Grand St,City Hall,24 Hour
ride_3,232,2018-05-01 01:35:22,McGinley Square,Lincoln Park,FREE Bonus Month with Annual Membership
ride_4,190,2018-05-01 02:06:40,City Hall,Grove St PATH,24 Hour
ride_5,303,2018-05-01 04:32:16,Oakland Ave,Sip Ave,Annual Membership
ride_6,176,2018-05-01 04:40:01,McGinley Square,Sip Ave,Annual Membership
ride_7,577,2018-05-01 05:15:23,Baldwin at Montgomery,Grove St PATH,Annual Membership from Citi Bike App
ride_8,830,2018-05-01 05:25:41,Oakland Ave,City Hall,Annual Membership
ride_9,395,2018-05-01 05:18:42,Baldwin at Montgomery,Grove St PATH,Annual Membership
ride_10,170,2018-05-01 05:16:43,Hilltop,Sip Ave,$25 Off Annual Membership

In [60]:
new_citi_bike_data.loc[::2, ::2]

,tripduration,stoptime,start station name,end station name,name_localizedValue
ride_1,338,2018-05-01 00:10:25,Harborside,Newport Pkwy,Annual Membership
ride_3,232,2018-05-01 01:35:22,McGinley Square,Lincoln Park,FREE Bonus Month with Annual Membership
ride_5,303,2018-05-01 04:32:16,Oakland Ave,Sip Ave,Annual Membership
ride_7,577,2018-05-01 05:15:23,Baldwin at Montgomery,Grove St PATH,Annual Membership from Citi Bike App
ride_9,395,2018-05-01 05:18:42,Baldwin at Montgomery,Grove St PATH,Annual Membership

In [62]:
new_citi_bike_data.iloc[2:10:2, :8]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300

In [64]:
new_citi_bike_data.loc[::,['start station name']]

            start station name
ride_1              Harborside
ride_2                Grand St
ride_3         McGinley Square
ride_4               City Hall
ride_5             Oakland Ave
ride_6         McGinley Square
ride_7   Baldwin at Montgomery
ride_8             Oakland Ave
ride_9   Baldwin at Montgomery
ride_10                Hilltop

In [65]:
new_citi_bike_data.loc[::,['start station name', 'starttime', 'bikeid']]

            start station name            starttime  bikeid
ride_1              Harborside  2018-05-01 00:04:47   33558
ride_2                Grand St  2018-05-01 01:31:10   33593
ride_3         McGinley Square  2018-05-01 01:31:29   29217
ride_4               City Hall  2018-05-01 02:03:29   29662
ride_5             Oakland Ave  2018-05-01 04:27:12   15271
ride_6         McGinley Square  2018-05-01 04:37:05   29298
ride_7   Baldwin at Montgomery  2018-05-01 05:05:46   33619
ride_8             Oakland Ave  2018-05-01 05:11:50   33624
ride_9   Baldwin at Montgomery  2018-05-01 05:12:07   26300
ride_10                Hilltop  2018-05-01 05:13:52   33555

In [66]:
# We want same columns values for ride_3 and ride_5
new_citi_bike_data.loc[['ride_3', 'ride_5'],['start station name', 'starttime', 'bikeid']]

       start station name            starttime  bikeid
ride_3    McGinley Square  2018-05-01 01:31:29   29217
ride_5        Oakland Ave  2018-05-01 04:27:12   15271

In [68]:
new_citi_bike_data.iloc[[2, 4], [1, 2, 0]]

                  starttime             stoptime  tripduration
ride_3  2018-05-01 01:31:29  2018-05-01 01:35:22           232
ride_5  2018-05-01 04:27:12  2018-05-01 04:32:16           303

In [69]:
arr1 = np.random.randint(10, 20, 5)
arr1

array([17, 12, 10, 13, 15])

In [70]:
arr1 > 15

array([ True, False, False, False, False])

In [71]:
arr1[arr1 > 15]

array([17])

In [73]:
# Conditional Indexing
new_citi_bike_data[new_citi_bike_data['tripduration']>200]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber

In [75]:
# In our original datafrmae, we want to access all the trips where start station name is Grand St
citi_bike_data[citi_bike_data['start station name'] == 'Grand St']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
104,125,2018-05-01 07:23:51,2018-05-01 07:25:57,3681,Grand St,3275,Columbus Drive,29245,Annual Membership,Subscriber
276,171,2018-05-01 08:35:39,2018-05-01 08:38:30,3681,Grand St,3183,Exchange Place,29201,Annual Membership,Subscriber
381,25958,2018-05-01 09:29:09,2018-05-01 16:41:48,3681,Grand St,304,Broadway & Battery Pl,29672,Citi Bike Annual Membership,Subscriber
400,228,2018-05-01 09:56:13,2018-05-01 10:00:01,3681,Grand St,3185,City Hall,33563,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32057,612,2018-05-30 08:27:06,2018-05-30 08:37:19,3681,Grand St,3277,Communipaw & Berry Lane,29276,Annual Membership,Subscriber
32180,263,2018-05-30 09:14:22,2018-05-30 09:18:46,3681,Grand St,3186,Grove St PATH,26299,Annual Membership,Subscriber
32238,247,2018-05-30 10:00:17,2018-05-30 10:04:25,3681,Grand St,3186,Grove St PATH,26303,Annual Membership,Subscriber
32246,227,2018-05-30 10:08:49,2018-05-30 10:12:36,3681,Grand St,3639,Harborside,26210,Annual Membership,Subscriber
32261,112,2018-05-30 10:28:25,2018-05-30 10:30:18,3681,Grand St,3275,Columbus Drive,29533,Annual Membership,Subscriber

In [79]:
# Access the trip data for first 8 columns for all the rides where tripduration is more than 200

new_citi_bike_data[new_citi_bike_data['tripduration']>200].iloc[::, :8]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300

In [81]:
new_citi_bike_data.loc[new_citi_bike_data['tripduration']>200, 'tripduration':'bikeid']

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid
ride_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558
ride_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593
ride_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217
ride_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271
ride_7,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619
ride_8,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624
ride_9,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300